### ISSUE TITLE
Outdated intrepreter and api

### ISSUE THREAD

**Issue by atesin** [oblerion/ZeroBrane-Studio-with-TIC-80#1]
hi.. i follow instructions in code > readme.md ... but instead, this logs are printed in zbs output tab

```
Program starting as 'D:/Games/TIC-80/tic80.exe C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\maze.tic -code C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\maze.lua'.
Program 'tic80.exe' started in 'D:\Users\atesin\Desktop\love2d\minimal' (pid: 11672).
Usage: tic80 [cart] [options]

TIC-80 startup options:

    -h, --help        show this help message and exit
    --skip            skip startup animation
    --volume=<int>    global volume value [0-15]
    --cli             console only output
    --fullscreen      enable fullscreen mode
    --vsync           enable VSYNC
    --soft            use software rendering
    --fs=<str>        path to the file system folder
    --scale=<int>     main window scale
    --cmd=<str>       run commands in the console
    --keepcmd         re-execute commands on every run
    --version         print program version
    --crt             enable CRT monitor effect
error: unknown option `-code`
Program completed in 0.21 seconds (pid: 11672).
```
note: i am also experimenting with some love2d tutorial projects, but have NOTHING TO DO with tic80 ... they are in "projects" tab, while tic80 are single lua files in "outline" tab

also ~~i would like to exists some kind of autoexec option~~, maybe with some command line like `<path_to>\tic80.exe myCart.tic --cmd="import code myCart.lua"` instead

**Comment by oblerion** [comment]
You need old version 0.80 of tic80 for run this pluging, 
 because api and interpreter have not update since 2019.
 
 I am not the writter of code, i need time for understand what it do.

**Comment by oblerion** [comment]
Interpreter is fix and optimize

**Comment by atesin** [comment]
thank you so much ..  in behalf every anonymous people that could find this interpreter useful
