### ISSUE TITLE
document normal usage instructions

### ISSUE THREAD

**Issue by atesin** [oblerion/ZeroBrane-Studio-with-TIC-80#7]
hi... currently in readme.md there are instructions on how to install and configure package (by copying to /packages folder and edit a config file)... but after that...

please also add instructions on how to use it daily as it was intended for, maybe with a quick example

now a new feature "interpreters" was added (TIC-80_LUA and TIC-80_TIC) that is mentioned, but we have no idea how to use it either xD

**Comment by oblerion** [comment]
new section added in README.md ^^
